
;---------------------------------------------------------------------------
;  steps.inc - steps include file for openprs rcll2016 agent
;
;  Created: Tue Jan 17 15:43:00 2017
;  Copyright  2017  Mostafa Gomaa [gomaa@kbsg.rwth-aachen.de]
;  Licensed under GPLv2+ license, cf. LICENSE file
;---------------------------------------------------------------------------


declare op_predicate 	step
declare be 				step-failed